#ifndef __ZSON_H__
#define __ZSON_H__

enum ZSON_entity_type{
    ZSON_PADDING = 0,
    ZSON_NULL,
    ZSON_TRUE,
    ZSON_FALSE,
    ZSON_INT8,
    ZSON_INT16,
    ZSON_INT32,
    ZSON_INT64,
    ZSON_UINT8,   
    ZSON_UINT16,
    ZSON_UINT32,
    ZSON_UINT64,
    ZSON_FLOAT32,
    ZSON_FLOAT64,
    ZSON_STRING,
    ZSON_STRING4,
    ZSON_STRING8,
    ZSON_STRING12,
    ZSON_OBJECT,
    ZSON_ARRAY,
    ZSON_ARRAY_INT8,
    ZSON_ARRAY_INT16,
    ZSON_ARRAY_INT32,
    ZSON_ARRAY_INT64,
    ZSON_ARRAY_UINT8,
    ZSON_ARRAY_UINT16,
    ZSON_ARRAY_UINT32,
    ZSON_ARRAY_UINT64,
    ZSON_ARRAY_FLOAT32,
    ZSON_ARRAY_FLOAT64,
};



#endif
